### ISSUE TITLE
Anti bot error

### ISSUE THREAD

**Issue by brunoqs** [small-sunshines/google-parser#2]
How can i bypass google antibot? is there any way?

**Comment by dalbodeule** [comment]
I continued exploring the cause, and eventually found out that it wasn't what I could do. Soon this library will be depreated.

**Comment by brunoqs** [comment]
@dalbodeule 
am i willing to make some updates to it, or do you think it is not possible?

**Comment by dalbodeule** [comment]
Google seems to have strengthened its AntiBot policy these days.

I think the key is to make the host running this program look like Bot.
Secondly, image retrieval is thought to be simple to modify. But it also avoids the AntiBot policy and requires some image parsing source to be modified.

**Comment by brunoqs** [comment]
I managed to use it by testing if the google response comes with the string 'Your Search -', its works well for now, but idk if google will block my IP
```javascript

const search = `site:${blogUrl.value} <string-to-search>;
const url = `https://cors-anywhere.herokuapp.com/https://www.google.com/searchq=${encodeURIComponent(search)}&hl=en-US`;
const res = await axios.get(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" +
          "(KHTML, like Gecko) Chrome/76.0.3809.146 Whale/2.6.88.11 Safari/537.36",
      }
});
if (res.data.includes('Your search -')) {
      console.log('SEARCH Not Found')
} else {
      console.log('SEARCH Found')
}

```
